sim_metric: 'cosine' # choose form ['cosine', 'l2']
keep_hard: True # True for hard examples
Kmeans_with_cos_dist: True # True for using cosine similarity for kmeans clustering
emb_memory_loc: "../embeddings.mmap"
text_emb_memory_loc: None
paths_memory_loc: "../paths.mmap"
sorted_clusters_file_loc: "sorted_clusters"
save_folder: "result"
path_str_dtype: "U200"
ncentroids: 50
dataset_size: 2500 
emb_size: 2048
niter: 100
seed: 1234
